// Mock data for the OEM Rebuilds website

// Car makes and models
const carData = {
  makes: ["Toyota", "Honda", "Ford", "BMW", "Mercedes", "Audi", "Nissan", "Tata",
    "Hyundai", "Maruti", "Kia", "Volkswagen", "Chevrolet", "Renault", "Skoda",
    "Fiat", "Mahindra", "Isuzu", "Bajaj_Auto", "Ashok_Leyland", "Hindustan_Motors",
    "Royal_Enfield", "Ferrari", "Lamborghini", "Porsche", "Ducati", "KTM", "Yamaha",
    "Rolls_Royce", "Aston_Martin", "Bugatti", "Maserati", "Mitsubishi", "MG",
    "Koenigsegg", "Dodge", "Volvo", "Land_Rover", "Subaru", "Audi", "Ola",
    "Ather", "Bajaj", "TVS" ],
  models: {
    Toyota: ["Camry", "Corolla", "RAV4", "Highlander", "Tacoma","Innova", "Fortuner", "Yaris", "Land Cruiser", "Hilux","Etios", "Etios-Liva", "Glanza", "Supra MK5", "Urban Cruiser","C-HR", "Vios", "Avanza", "Rush", "Agya"],
    Honda: ["Civic", "Accord", "CR-V", "Pilot", "Odyssey", "Brio","City", "Jazz", "Amaze", "WR-V","BR-V", "HR-V", "ZRV", "Legend", "Crosstour"],
    Ford: ["F-150", "Mustang", "Explorer", "Escape", "Focus", "Fusion","Endeavour", "EcoSport", "Fiesta", "Mondeo","Ranger", "Everest", "Mustang Mach-E", "Bronco", "Transit"],
    BMW: ["3 Series", "5 Series", "X3", "X5", "7 Series", "X1","Z4", "M3", "M5", "X7","i3", "i4", "iX", "M4", "M8"],
    Mercedes: ["C-Class", "E-Class", "S-Class", "GLC", "GLE", "GLS","A-Class", "B-Class", "CLA", "GLA","SL-Class", "SLC", "EQC", "AMG GT", "G-Class"],
    Audi: ["A4", "A6", "Q5", "Q7", "A8", "Q3", "TT","A3", "A5", "Q8", "e-tron","RS5", "RS7", "S4", "S6", "S8"],
    Nissan: ["Altima", "Maxima", "Rogue", "Patrol", "Sentra", "Murano","370Z", "GT-R", "Armada", "Magnite","Juke", "Kicks", "Leaf", "Frontier", "Titan","Sunny", "Micra", "Teana", "X-Trail", "Datsun GO"],
    Tata: ["Nexon", "Harrier", "Safari", "Altroz", "Tiago","Tigor", "Hexa", "Zest", "Indica", "Indigo","Punch", "Magic IRIS", "Venture"],
    Hyundai: ["Creta", "Verna", "i20", "Tucson", "Kona","Elantra", "Venue", "Sonata", "Santa Fe","i10", "i30", "i40", "iX35"],
    Maruti: ["Swift", "Dzire", "Baleno", "Vitara Brezza", "Alto","Wagon R", "Ertiga", "S-Cross", "Celerio","XL6", "Ignis", "Kizashi"],
    Kia: ["Seltos", "Sonet", "Carnival", "Sportage", "Stinger","Rio", "Forte", "Optima", "Cadenza"],
    Volkswagen: ["Polo", "Vento", "Tiguan", "T-Roc", "Jetta","Passat", "Virtus", "Taigun", "ID.4"],
    Chevrolet: ["Sail", "Beat", "Cruze", "Tavera", "Captiva","Trailblazer", "Equinox", "Tracker"],
    Renault: ["Duster", "Kwid", "Captur", "Triber", "Lodgy","Kiger", "Fluence", "Scala"],
    Skoda: ["Octavia", "Superb", "Kodiaq", "Kushaq", "Rapid","Fabia", "Slavia", "Laura"],
    Fiat: ["Punto", "Linea", "Abarth", "500", "Panda","Tipo", "Ducato"],
    Mahindra: ["Thar", "XUV700", "Scorpio", "Bolero", "TUV300","KUV100", "Marazzo", "Alturas G4"],
    Isuzu: ["D-Max", "MU-X", "V-Cross", "D-Max S-Cab"],
    Bajaj_Auto: ["Pulsar", "Dominar", "Avenger", "Discover","Platina", "CT100", "V15"],
    Ashok_Leyland: ["Dost", "Partner", "Stile", "Boss","Comet", "Ecomet", "U-Truck"],
    Hindustan_Motors: ["Ambassador", "Contessa", "Landmaster","Morris Oxford", "Hindustan Trekker"],
    Royal_Enfield: ["Classic", "Bullet", "Himalayan", "Interceptor","Continental GT", "Thunderbird", "Meteor"],
    Ferrari: ["488", "F8", "Portofino", "Roma","SF90 Stradale", "LaFerrari", "California"],
    Lamborghini: ["Huracan", "Aventador", "Urus", "Gallardo","Sián", "Countach", "Murcielago"],
    Porsche: ["911", "Cayenne", "Macan", "Panamera","Boxster", "Cayman", "Taycan"],
    Ducati: ["Panigale", "Monster", "Multistrada", "Scrambler","Diavel", "Streetfighter", "XDiavel"],
    KTM: ["Duke", "RC", "Adventure", "390 Duke","250 Duke", "390 Adventure", "RC 200"],
    Yamaha: ["YZF-R1", "YZF-R3", "MT-09", "FZ-07","FZ-09", "Tracer 900", "XSR900"],
    Rolls_Royce: ["Phantom", "Ghost", "Cullinan","Wraith", "Dawn", "Silver Shadow"],
    Aston_Martin: ["DB11", "Vantage", "DBS", "Rapide","DBX", "Valkyrie", "One-77"],
    Bugatti: ["Chiron", "Veyron", "Divo", "Centodieci","La Voiture Noire", "EB110", "Chiron Super Sport"],
    Maserati: ["Ghibli", "Quattroporte", "Levante","Alfieri", "MC20", "GranTurismo"],
    Tesla: ["Model S", "Model 3", "Model X", "Model Y","Cybertruck", "Roadster"],
    Mithsubishi: ["Pajero", "Outlander", "ASX", "Eclipse Cross","Lancer", "Montero", "Galant"],
    Tata_Motors: ["Nexon EV", "Tigor EV", "Tiago EV","Harrier EV", "Safari EV"],
    Konigsegg: ["Agera", "Regera", "Jesko", "Gemera","CCX", "One:1", "CCXR"],
    Dodge: ["Charger", "Challenger", "Durango","Ram 1500", "Viper", "Dart"],
    Jeep: ["Wrangler", "Cherokee", "Grand Cherokee","Renegade", "Compass", "Gladiator"],
    Volvo: ["XC90", "XC60", "S60", "S90","V60", "V90", "C40 Recharge"],
    Land_Rover: ["Range Rover", "Discovery", "Defender","Evoque", "Velar", "Sport"],
    Subaru: ["Outback", "Forester", "Crosstrek","Impreza", "Legacy", "Ascent"],
    Audi: ["A4", "A6", "Q5", "Q7","A8", "Q3", "TT"],
    Ola: ["S1 Pro", "S1 Air", "S1X","S1 Ultra"],
    Ather: ["450X", "450 Plus", "450S","450R"],
    Bajaj: ["Chetak", "Pulsar EV", "Urbanite","Avenger EV"],
    TVS: ["iQube", "Zephyr", "Xtreme","Apache EV"],
  },
}

// Categories
const categories = [
  {
    id: "engine",
    name: "Engine Parts",
    icon: "tool",
    description: "Pistons, Gaskets, Valves & more",
    color: "engine",
  },
  {
    id: "body",
    name: "Body Parts",
    icon: "truck",
    description: "Bumpers, Doors, Mirrors & more",
    color: "body",
  },
  {
    id: "accessories",
    name: "Accessories",
    icon: "zap",
    description: "Lights, Wipers, Mats & more",
    color: "accessories",
  },
  {
    id: "other",
    name: "Other Parts",
    icon: "settings",
    description: "Filters, Belts, Sensors & more",
    color: "other",
  },
]

// Products
const products = [
  {
    id: 1,
    name: "Engine Piston Set",
    price: 129.99,
    image: "/placeholder.svg?height=300&width=300",
    category: "engine",
    brand: "OEM Toyota",
    compatibility: ["Toyota Camry", "Toyota Corolla"],
    inStock: true,
  },
  {
    id: 2,
    name: "Brake Pad Kit",
    price: 79.99,
    image: "/placeholder.svg?height=300&width=300",
    category: "brakes",
    brand: "OEM Honda",
    compatibility: ["Honda Civic", "Honda Accord"],
    inStock: true,
  },
  {
    id: 3,
    name: "Headlight Assembly",
    price: 199.99,
    image: "/placeholder.svg?height=300&width=300",
    category: "accessories",
    brand: "OEM Ford",
    compatibility: ["Ford F-150", "Ford Mustang"],
    inStock: true,
  },
  {
    id: 4,
    name: "Oil Filter",
    price: 12.99,
    image: "/placeholder.svg?height=300&width=300",
    category: "other",
    brand: "OEM BMW",
    compatibility: ["BMW 3 Series", "BMW 5 Series"],
    inStock: false,
  },
  {
    id: 5,
    name: "Alternator",
    price: 149.99,
    image: "/placeholder.svg?height=300&width=300",
    category: "engine",
    brand: "OEM Nissan",
    compatibility: ["Nissan Altima", "Nissan Maxima"],
    inStock: true,
  },
  {
    id: 6,
    name: "Side Mirror",
    price: 89.99,
    image: "/placeholder.svg?height=300&width=300",
    category: "body",
    brand: "OEM Mercedes",
    compatibility: ["Mercedes C-Class", "Mercedes E-Class"],
    inStock: true,
  },
  {
    id: 7,
    name: "Air Filter",
    price: 19.99,
    image: "/placeholder.svg?height=300&width=300",
    category: "other",
    brand: "OEM Audi",
    compatibility: ["Audi A4", "Audi Q5"],
    inStock: true,
  },
  {
    id: 8,
    name: "Spark Plugs (Set of 4)",
    price: 29.99,
    image: "/placeholder.svg?height=300&width=300",
    category: "engine",
    brand: "OEM Toyota",
    compatibility: ["Toyota RAV4", "Toyota Highlander"],
    inStock: true,
  },
]

// Extract unique categories and brands for filters
const productCategories = [...new Set(products.map((product) => product.category))]
const productBrands = [...new Set(products.map((product) => product.brand))]

